const accountStatement = "account-statement"
const gameDetail = "/game-detail/:sportId/:matchId/:selectionId"
const casino = "/casino/:casinoType"
const home = "/"
const currentBet = "/current-bet"
const login = "/login"
const aviatorLobby = "/aviator-lobby"
const casinoLobby = "/casino-lobby/:id/:name"
const allSport = "/sport/:id"
const changePasswordPage = "/changepassword"
const liveCasinoPage = "/livecasino"
const slotCasinoPage = "/slot"
const fantasyCasinoPage = "/fantasy"
export {fantasyCasinoPage,slotCasinoPage,liveCasinoPage,accountStatement,gameDetail,casino,home,currentBet,login,aviatorLobby,casinoLobby,allSport,changePasswordPage}